package Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jessica
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namaAnggota = new javax.swing.JLabel();
        logoITB = new javax.swing.JLabel();
        informatika = new javax.swing.JLabel();
        backgroundAbout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        namaAnggota.setFont(new java.awt.Font("Kartika", 1, 20)); // NOI18N
        namaAnggota.setForeground(new java.awt.Color(1, 61, 79));
        namaAnggota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaAnggota.setText("<html><center>Edwin Wijaya 13513040<br><br> Elvan Owen 13513082<br><br> Jessica Andjani 13513086<br><br> Vicko Novianto 13513092</center> </html>");
        namaAnggota.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(namaAnggota);
        namaAnggota.setBounds(280, 160, 270, 200);

        logoITB.setIcon(new javax.swing.ImageIcon("D:\\Users\\Jessica\\Pictures\\Background\\ITB.png")); // NOI18N
        logoITB.setAlignmentY(0.0F);
        jPanel1.add(logoITB);
        logoITB.setBounds(360, 370, 100, 110);

        informatika.setFont(new java.awt.Font("Kartika", 1, 16)); // NOI18N
        informatika.setForeground(new java.awt.Color(1, 61, 79));
        informatika.setText("INFORMATIKA ITB");
        jPanel1.add(informatika);
        informatika.setBounds(350, 480, 150, 24);

        backgroundAbout.setIcon(new javax.swing.ImageIcon("D:\\Users\\Jessica\\Pictures\\Background\\about.png")); // NOI18N
        jPanel1.add(backgroundAbout);
        backgroundAbout.setBounds(0, 0, 800, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundAbout;
    private javax.swing.JLabel informatika;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoITB;
    private javax.swing.JLabel namaAnggota;
    // End of variables declaration//GEN-END:variables
}
