/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author Jessica
 */
public class HowToPlay extends javax.swing.JFrame {

    /**
     * Creates new form HowToPlay
     */
    public HowToPlay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Langkah1 = new javax.swing.JLabel();
        Langkah2 = new javax.swing.JLabel();
        Langkah3 = new javax.swing.JLabel();
        backgroundHowToPlay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Langkah1.setFont(new java.awt.Font("Kartika", 1, 14)); // NOI18N
        Langkah1.setText("<html>\n    Hewan - hewan akan bermunculan pada saat permainan di mulai.<br>\n   Dan terdapat huruf - huruf pada tubuh setiap hewan.<br>\n  Ketikkan huruf  - huruf yang terdapat pada tubuh hewan pada kotak yang telah disediakan.\n</html>");
        jPanel1.add(Langkah1);
        Langkah1.setBounds(20, 340, 240, 150);

        Langkah2.setFont(new java.awt.Font("Kartika", 1, 14)); // NOI18N
        Langkah2.setText("<html>    Jika kata yang diketikkan sesuai dengan huruf-huruf yang terdapat pada tubuh hewan.<br>    Hewan akan menghilang dan score akan bertambah. </html>");
        jPanel1.add(Langkah2);
        Langkah2.setBounds(280, 340, 250, 110);

        Langkah3.setFont(new java.awt.Font("Kartika", 1, 14)); // NOI18N
        Langkah3.setText("<html>    Jika hewan mencapai ujung layar dan huruf pada tubuh hewan tidak berhasil diketikkan,  maka   \tpermainan akan berakhir. </html>");
        jPanel1.add(Langkah3);
        Langkah3.setBounds(540, 340, 240, 90);

        backgroundHowToPlay.setIcon(new javax.swing.ImageIcon("D:\\Users\\Jessica\\Pictures\\Background\\howtoplay.png")); // NOI18N
        jPanel1.add(backgroundHowToPlay);
        backgroundHowToPlay.setBounds(0, 0, 800, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Langkah1;
    private javax.swing.JLabel Langkah2;
    private javax.swing.JLabel Langkah3;
    private javax.swing.JLabel backgroundHowToPlay;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
